spring.application.name=support_trainer

#Porta server predefinita
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/supporto_trainer
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#come gestire le tabelle
#update → comodo in dev, aggiorna lo schema senza cancellare tutto
#create → ricrea da zero a ogni avvio (cancella i dati)
#create-drop → come create, e in più drop allo stop
#validate → controlla che lo schema esista e sia coerente, non modifica → in produzione
#none → non fa nulla 
spring.jpa.hibernate.ddl-auto=none

#Per vedere le query SQL nel terminale
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true