ALTER TABLE invite_codes
    MODIFY COLUMN expires_at DATETIME(6) NOT NULL,
    MODIFY COLUMN used_at DATETIME(6) NULL,
    MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NOT NULL
        DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
