ALTER TABLE email_verification_tokens
    MODIFY COLUMN expires_at DATETIME(6) NOT NULL,
    MODIFY COLUMN used_at DATETIME(6) NULL,
    MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);
