ALTER TABLE availability_slots
    MODIFY COLUMN start_date_time DATETIME(6) NOT NULL,
    MODIFY COLUMN end_date_time DATETIME(6) NOT NULL,
    MODIFY COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    MODIFY COLUMN updated_at DATETIME(6) NOT NULL
        DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6);
